targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/features/transactions/domain/entities/**.dart
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/features/transactions/domain/entities/**.dart 