name: enki_finance
description: A personal finance management app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  supabase_flutter: ^2.0.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  flutter_slidable: ^4.0.0
  flutter_native_splash: ^2.3.8
  go_router: ^14.8.0
  url_launcher: ^6.2.2
  package_info_plus: ^8.2.1
  flutter_secure_storage: ^10.0.0-beta.4
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.2
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  device_info_plus: ^11.3.0
  connectivity_plus: ^6.1.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  flex_color_scheme: ^8.1.0
  google_fonts: ^6.1.0
  supabase_auth_ui: ^0.5.4
  equatable: ^2.0.5
  encrypt: ^5.0.3
  app_links: ^6.3.3
  sentry_flutter: ^8.13.0
  firebase_analytics: ^11.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  mockito: ^5.4.4
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  http: ^1.1.0
  crypto: ^3.0.3
